-- Databricks notebook source
use catalog workspacefeb122026

-- COMMAND ----------

CREATE SCHEMA AMAZONDATABASE

-- COMMAND ----------

use AMAZONDATABASE

-- COMMAND ----------

CREATE TABLE CUSTOMERS_DATA
(
CustomerKey INT ,			 
CustomerName	VARCHAR(30), 
Gender		CHAR(1)	,  
MStatus		CHAR(1)	,
Income		FLOAT	
);

INSERT INTO CUSTOMERS_DATA VALUES (1001, 'JOHN', 'M','M', 250000);
INSERT INTO CUSTOMERS_DATA VALUES (1002, 'AMIN',  'M','S', 150000);
INSERT INTO CUSTOMERS_DATA VALUES (1003, 'SAI',  'M','S', 200000);
INSERT INTO CUSTOMERS_DATA VALUES (1004, 'SAISHA', 'M','S', 700000);

-- COMMAND ----------

CREATE TABLE PRODUCTS_DATA
(
ProductKey INT ,
ProductName	VARCHAR(30),
Class		CHAR(1) ,
Color		VARCHAR(20) ,
UnitPrice	FLOAT		
);


INSERT INTO PRODUCTS_DATA VALUES
  (101, 'CAPS', 'M', 'RED', 2),
  (102, 'CAPS', 'H', 'RED', 2),
  (103, 'GLOVES', 'M', 'GREEN', 2),
  (104, 'GLOVES', 'H', 'GREEN', 2),
  (105, 'ELECTRONICS-1', 'M', 'WHITE', 10),
  (106, 'ELECTRONICS-2', 'M', 'WHITE', 9);

-- COMMAND ----------

CREATE TABLE SALES_DATA 
(
  SaleID INT,
  CustKey INT,
  ProductKey INT,
  SaleAmount FLOAT,
  TaxAmount FLOAT,
  NetAmount FLOAT
);


-- COMMAND ----------

INSERT INTO SALES_DATA
SELECT
  monotonically_increasing_id() + 100001 AS SaleID,
  CustKey,
  ProductKey,
  SaleAmount,
  TaxAmount,
  (SaleAmount + TaxAmount) AS NetAmount
FROM VALUES
  (1001, 101, 6300, 130),
  (1002, 104, 9500, 180),
  (1003, 101, 2300, 330),
  (1001, 104, 1900, 180),
  (1002, 102, 3020, 130),
  (1003, 104, 9200, 380),
  (1001, 105, 3100, 304),
  (1002, 105, 1900, 840),
  (1003, 102, 5300, 320),
  (1003, 104, 9600, 280),
  (1002, 102, 3070, 230),
  (1004, 104, 91200, 3800)
AS src(CustKey, ProductKey, SaleAmount, TaxAmount);


-- COMMAND ----------

select * from SALES_DATA

-- COMMAND ----------

INSERT INTO SALES_DATA
SELECT
  ROW_NUMBER() OVER (ORDER BY CustKey) + 100001 AS SaleID,
  CustKey,
  ProductKey,
  SaleAmount,
  TaxAmount,
  (SaleAmount + TaxAmount) AS NetAmount
FROM VALUES
  (1001, 101, 6300, 130),
  (1002, 104, 9500, 180),
  (1003, 101, 2300, 330),
  (1001, 104, 1900, 180),
  (1002, 102, 3020, 130),
  (1003, 104, 9200, 380),
  (1001, 105, 3100, 304),
  (1002, 105, 1900, 840),
  (1003, 102, 5300, 320),
  (1003, 104, 9600, 280),
  (1002, 102, 3070, 230),
  (1004, 104, 91200, 3800)
AS src(CustKey, ProductKey, SaleAmount, TaxAmount);


-- COMMAND ----------

SELECT * FROM PRODUCTS_DATA 
INNER JOIN SALES_DATA
ON PRODUCTS_DATA.ProductKey = SALES_DATA.ProductKey

-- COMMAND ----------

SELECT PRODUCTS_DATA.Class, PRODUCTS_DATA.Color, PRODUCTS_DATA.ProductName,  
SALES_DATA.SaleAmount, SALES_DATA.TaxAmount
FROM PRODUCTS_DATA 
JOIN SALES_DATA
ON PRODUCTS_DATA.ProductKey =  SALES_DATA.ProductKey

-- COMMAND ----------

SELECT P.Class, P.Color, P.ProductName,  
SUM(S.SaleAmount) AS TOTALSALES
FROM PRODUCTS_DATA AS P
INNER JOIN SALES_DATA AS S
ON P.ProductKey =  S.ProductKey 
WHERE P.Class = 'M'
GROUP BY P.Class, P.Color, P.ProductName

-- COMMAND ----------

SELECT P.ProductName, P.Class, P.Color,
SUM(S.SALEAMOUNT) AS TOTAL_SALES, COUNT(C.CustomerKey) AS CUSTOMERCOUNT 
FROM PRODUCTS_DATA  AS P
INNER JOIN SALES_DATA AS S
ON S.ProductKey = P.ProductKey 
INNER JOIN CUSTOMERS_DATA AS C
ON C.CustomerKey = S.CustKey 
GROUP BY P.ProductName, P.Class, P.Color 
ORDER BY TOTAL_SALES DESC

-- COMMAND ----------

SELECT P.ProductName, P.Class, P.Color,
SUM(S.SALEAMOUNT) AS TOTAL_SALES, COUNT(C.CustomerKey) AS CUSTOMERCOUNT,
CASE 
WHEN COUNT(C.CustomerKey) > 2 THEN 'GOOD CUSTOMER COUNT' 
WHEN COUNT(C.CustomerKey) BETWEEN 1 AND 2 THEN 'AVG CUSTOMER COUNT' 
ELSE 'LOW CUSTOMER COUNT' END AS CUSTOMER_GRADE 
FROM PRODUCTS_DATA  AS P
INNER JOIN SALES_DATA AS S
ON S.ProductKey = P.ProductKey 
INNER JOIN CUSTOMERS_DATA AS C
ON C.CustomerKey = S.CustKey 
GROUP BY P.ProductName, P.Class, P.Color 
ORDER BY TOTAL_SALES DESC

-- COMMAND ----------

CREATE VIEW VW_AGGR_SALES
AS
SELECT P.ProductName, P.Class, P.Color,
SUM(S.SALEAMOUNT) AS TOTAL_SALES, COUNT(C.CustomerKey) AS CUSTOMERCOUNT,
CASE 
WHEN COUNT(C.CustomerKey) > 2 THEN 'GOOD CUSTOMER COUNT' 
WHEN COUNT(C.CustomerKey) BETWEEN 1 AND 2 THEN 'AVG CUSTOMER COUNT' 
ELSE 'LOW CUSTOMER COUNT' END AS CUSTOMER_GRADE 
FROM PRODUCTS_DATA  AS P
INNER JOIN SALES_DATA AS S
ON S.ProductKey = P.ProductKey 
INNER JOIN CUSTOMERS_DATA AS C
ON C.CustomerKey = S.CustKey 
GROUP BY P.ProductName, P.Class, P.Color 
ORDER BY TOTAL_SALES DESC